package aimas.entities;

import aimas.Command;

import java.util.ArrayList;

public class Agent extends Entity{
    //public static final Agent NO_AGENT = new Agent(Color.BLUE, -1);

    private int number;
    // commands this agent has to do; to be filled during runtime of the program
    private ArrayList<Command> actions = new ArrayList<>();
    public int getNumber() {
        return number;
    }
    public ArrayList<Command> getActions() {
        return actions;
    }
    public void setNumber(int number) {
        this.number = number;
    }

    public Agent(Color color, int number) {
        //this.currentCell = currentCell;
        this.color = color;
        this.number = number;
    }

    public Agent(Agent original){
        this.color = original.color;
        this.number = original.number;
    }

    public String act(){
        return Command.EVERY[3].toString(); // this is what agent is gonna do
        // TODO make it fetch commands from list generated by A*
    }

    @Override
    public String toString() {
        return "" + getNumber()/* + " on: " + currentCell.getI() + " : " + currentCell.getJ()*/;
    }
}
