package aimas.competition;

import aimas.Command;
import aimas.Launcher;
import aimas.MapParser;
import aimas.Node;
import aimas.actions.Action;
import aimas.actions.AtomicAction;
import aimas.actions.expandable.SolveLevelAction;
import aimas.aiutils.MASolver;
import aimas.aiutils.BdiHtnFsmSolver;
import aimas.aiutils.BestFirstSearch;
import aimas.aiutils.World;
import aimas.board.Cell;
import aimas.board.entities.Agent;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.*;

/**
 * Client to run against levels
 */
/*
Basic usage for the server is either of:
   $ java -jar server.jar -c <command> -l <level path> <arguments>
   $ java -jar server.jar -o <file>

   Command to run our program will be as follows:
   Running from server, in quotes:

   java -cp ".:aimas/competition/*" aimas/competition/Client

   i.e something like:

   java -Dsun.java2d.opengl=true
   -jar server.jar -l levels/SAsokobanLevel96.lvl -c "java -cp ".:aimas/competition/*" aimas/competition/Client" -g

   Compiling:
   From the folder with server jar, and where competition folder has dependency jars:

   javac -cp ".:aimas/competition/*" aimas/competition/Client.java
 */
public class Client {

    private static BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
    private static boolean isMA = false;
    public static void main(String[] args) {
        System.err.println("Hello from Client. I am sending this using the error outputstream.");
        ArrayList<ArrayList<Cell>> level = new ArrayList<>();
        try {
            level = InputLevelReader.getLevel(in);
        }
        catch (IOException ex){
            // Nowhere to write to or nothing to read (latter unlikely)
        }
        System.err.println(InputLevelReader.getAgentCellCoords().get(0)); // just print first agent's position
        System.err.println("Level read successfully");
        System.err.println("Heuristic used: " + Launcher.HEURISTIC_USED.toString());

        // Try to solve level
        Node node = new Node(null);
        node.setLevel(level);
        node.setBoxCellCoords(Node.copyList(InputLevelReader.getBoxCellCoords()));
        node.setAgentCellCoords(Node.copyList(InputLevelReader.getAgentCellCoords()));
        node.setGoalCellCoords(Node.copyList(InputLevelReader.getGoalCellCoords()));
        node.setTunnelCellCoords(Node.copyList(InputLevelReader.getTunnelCellCoords()));
        node.setSpaceCells(Node.copyList(InputLevelReader.getSpaceCellCoords()));

        if (node.getAgents().size()>1){
            isMA = true;
        }
        if (isMA){
            List<String> Solution = MASolver.getSolutionForLevel(node);
            for (String string : Solution){
                System.err.println(string);
            }
            for (String string : Solution){
                System.out.println(string);
            }
        }
        else{
            World world =  new World(node);
            MapParser parser = new MapParser(node.getLevel());
            parser.parseMap(Node.getSpaceCellCoords(), node.getLevel());
            BdiHtnFsmSolver.cellWeights = parser.getCellWeights();
            SolveLevelAction solveLevel = new SolveLevelAction(node, BdiHtnFsmSolver.cellWeights);
            Agent agent = world.getState().getAgents().get(0);
            ArrayList<Command> Solution = BdiHtnFsmSolver.HTNBDIFSM(agent, solveLevel, world);
            for (Command command : Solution){
                System.out.println(command.toString());
            }
            try{
                Thread.sleep(300);
            }
            catch (Exception e){
                e.printStackTrace();
            }
            System.err.println("Number of nodes generated by A*: " + Node.nodeCount);
        }
    }
}
